secrets:
  groq_api_key:
    file: /home/cnurmi/docker/secrets/groq_api_key
  mealie_api_key:
    file: /home/cnurmi/docker/secrets/mealie_api_key

services:
  social-to-mealie:
    restart: unless-stopped
    image: ghcr.io/cnurmi/social-to-mealie:latest
    container_name: social-to-mealie
    secrets:
      - groq_api_key
      - mealie_api_key
    environment:
      - TEXT_PROVIDER=groq
      - TEXT_MODEL=llama-3.3-70b-versatile
      - MEALIE_URL=http://mealie:9000
      - MEALIE_GROUP_NAME=home
      - LOCAL_TRANSCRIPTION_MODEL=Xenova/whisper-base
      - YTDLP_VERSION=latest
    ports:
      - 4000:3000
    security_opt:
      - no-new-privileges:true
